import type { Metadata } from "next";
import { Nunito } from 'next/font/google'
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NunitoFont = Nunito({
  weight: ["300", "400", "600", "700"],
  subsets: ['latin'],
  fallback: ['sans-serif']
});

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={`${NunitoFont.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
